"""
Interface generation pipeline that combines EGNN-based global generation
with optional local GNN refinement.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Sequence, Tuple

import numpy as np
from pymatgen.core import Lattice, Structure

from interfaceml.core import adsorbate as adsorbate_builder
from interfaceml.core import layering

try:
    import torch
except Exception:
    torch = None  # type: ignore

try:
    from fullerene_diffusion_poc.units import denormalize_positions
except Exception:
    denormalize_positions = None  # type: ignore

from interfaceml.ai.local_gnn import LocalRefiner


@dataclass(frozen=True)
class InterfaceGenerationResult:
    bottom: Structure
    top: Structure
    combined: Structure
    metadata: Dict[str, Any]


class InterfaceAIGenerator:
    """High-level generator for EGNN + local GNN interface structures."""

    def __init__(
        self,
        *,
        fullerene_api: Any,
        local_refiner: Optional[LocalRefiner] = None,
    ) -> None:
        self.fullerene_api = fullerene_api
        self.local_refiner = local_refiner

    def generate_interface(
        self,
        *,
        base_structure: Structure,
        num_atoms: int = 60,
        num_samples: int = 1,
        ddim: bool = False,
        miller: Tuple[int, int, int] = (0, 0, 1),
        slab_thickness: float = 18.0,
        vacuum: float = 20.0,
        separation: float = 3.2,
        supercell_xy: Optional[Tuple[int, int]] = None,
        buffer: float = 10.0,
        xy_frac: Tuple[float, float] = (0.5, 0.5),
        termination: Optional[str] = None,
        layer_tol: float = 1.5,
        refine_scope: str = "adsorbate",
    ) -> InterfaceGenerationResult:
        if self.fullerene_api is None:
            raise RuntimeError("Fullerene API is required for global EGNN generation.")

        if torch is None or denormalize_positions is None:
            raise RuntimeError("PyTorch and fullerene_diffusion_poc are required for EGNN generation.")

        results = self.fullerene_api.generate(
            num_carbon=int(num_atoms),
            num_samples=int(num_samples),
            ddim=bool(ddim),
            return_trajectory=False,
        )
        if not results:
            raise RuntimeError("No structures were generated by the fullerene API.")

        sample = results[0]
        positions = np.asarray(sample["positions"], dtype=float)
        positions = _denormalize_positions(positions, num_atoms)

        adsorbate_struct = _adsorbate_structure_from_positions(positions)

        bottom, top, combined, choice = adsorbate_builder.build_adsorbate_interface(
            base_structure,
            adsorbate_struct,
            miller=miller,
            slab_thickness=slab_thickness,
            vacuum=vacuum,
            separation=separation,
            supercell_xy=supercell_xy,
            buffer=buffer,
            xy_frac=xy_frac,
            termination=termination,
            layer_tol=layer_tol,
            rotation=None,
        )

        metadata: Dict[str, Any] = {
            "supercell": {"nx": choice.nx, "ny": choice.ny},
            "termination": choice.termination,
            "termination_top": list(choice.termination_top),
            "termination_bottom": list(choice.termination_bottom),
            "local_refiner_used": False,
            "local_refiner_trained": False,
        }

        if self.local_refiner is not None:
            adsorbate_indices = list(range(len(bottom), len(bottom) + len(top)))
            interface_normal = layering.interface_normal_unit(bottom)
            combined = self.local_refiner.refine_structure(
                combined,
                adsorbate_indices=adsorbate_indices,
                interface_normal=interface_normal,
                refine_scope=refine_scope,
            )
            metadata["local_refiner_used"] = True
            metadata["local_refiner_trained"] = bool(getattr(self.local_refiner, "trained", False))

        return InterfaceGenerationResult(
            bottom=bottom,
            top=top,
            combined=combined,
            metadata=metadata,
        )


def _denormalize_positions(positions: np.ndarray, num_atoms: int) -> np.ndarray:
    if torch is None or denormalize_positions is None:
        return positions
    pos_tensor = torch.tensor(positions, dtype=torch.float32)
    pos_denorm = denormalize_positions(pos_tensor, int(num_atoms))
    return pos_denorm.detach().cpu().numpy()


def _adsorbate_structure_from_positions(positions: np.ndarray) -> Structure:
    if positions.size == 0:
        raise ValueError("No positions provided for adsorbate structure.")
    max_radius = float(np.linalg.norm(positions, axis=1).max())
    box_size = max(20.0, max_radius * 2.0 + 10.0)
    lattice = Lattice.cubic(box_size)
    species = ["C"] * positions.shape[0]
    return Structure(
        lattice,
        species,
        positions,
        coords_are_cartesian=True,
        to_unit_cell=False,
    )
