"""
Interface generation pipeline that combines EGNN-based global generation
with optional local GNN refinement.

Supports batch generation of multiple candidate structures in a single
call (Optimization 3).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Tuple

logger = logging.getLogger(__name__)

import numpy as np
from pymatgen.core import Lattice, Structure

from interfaceml.core import adsorbate as adsorbate_builder
from interfaceml.core import layering

try:
    import torch
except Exception:
    torch = None  # type: ignore

try:
    from fullerene_e3gen.units import denormalize_positions
except Exception:
    denormalize_positions = None  # type: ignore

from interfaceml.ai.local_gnn import LocalRefiner


@dataclass(frozen=True)
class InterfaceGenerationResult:
    bottom: Structure
    top: Structure
    combined: Structure
    metadata: Dict[str, Any]


class InterfaceAIGenerator:
    """High-level generator for EGNN + local GNN interface structures.

    Supports batch generation: ``generate_interface(..., num_samples=N)``
    returns a list of N ``InterfaceGenerationResult`` objects, each built
    from a different EGNN sample.
    """

    def __init__(
        self,
        *,
        fullerene_api: Any,
        local_refiner: Optional[LocalRefiner] = None,
    ) -> None:
        self.fullerene_api = fullerene_api
        self.local_refiner = local_refiner

    def generate_interface(
        self,
        *,
        base_structure: Structure,
        num_atoms: int = 60,
        num_samples: int = 1,
        ddim: bool = True,
        miller: Tuple[int, int, int] = (0, 0, 1),
        slab_thickness: float = 18.0,
        vacuum: float = 20.0,
        separation: float = 3.2,
        supercell_xy: Optional[Tuple[int, int]] = None,
        buffer: float = 10.0,
        xy_frac: Tuple[float, float] = (0.5, 0.5),
        termination: Optional[str] = None,
        layer_tol: float = 1.5,
        refine_scope: str = "adsorbate",
    ) -> List[InterfaceGenerationResult]:
        """Generate interface structures.

        Returns
        -------
        list of InterfaceGenerationResult
            One result per successfully generated sample.
        """
        if self.fullerene_api is None:
            raise RuntimeError("Fullerene API is required for global EGNN generation.")

        if torch is None or denormalize_positions is None:
            raise RuntimeError("PyTorch and fullerene_e3gen are required for EGNN generation.")

        results = self.fullerene_api.generate(
            num_carbon=int(num_atoms),
            num_samples=int(num_samples),
            ddim=bool(ddim),
            return_trajectory=False,
        )
        if not results:
            raise RuntimeError("No structures were generated by the fullerene API.")

        outputs: List[InterfaceGenerationResult] = []
        for sample_idx, sample in enumerate(results):
            try:
                # NOTE: api.generate() already returns positions in Angstroms
                # (it calls denormalize_positions internally). Do NOT
                # denormalize again — that was the root cause of the
                # "missing fullerene" bug (positions were scaled ~3.5x
                # too large, causing them to wrap/vanish in the cell).
                positions = np.asarray(sample["positions"], dtype=float)
                # Skip completely NaN samples from unstable diffusion runs
                if np.isnan(positions).all():
                    logger.warning("Sample %d is all-NaN — skipping.", sample_idx)
                    continue
                # Guard against partial NaN
                if np.isnan(positions).any():
                    logger.warning(
                        "Sample %d has %d NaN values — replacing with 0.",
                        sample_idx, int(np.isnan(positions).sum()),
                    )
                    positions = np.nan_to_num(positions, nan=0.0)

                adsorbate_struct = _adsorbate_structure_from_positions(positions)

                bottom, top, combined, choice = adsorbate_builder.build_adsorbate_interface(
                    base_structure,
                    adsorbate_struct,
                    miller=miller,
                    slab_thickness=slab_thickness,
                    vacuum=vacuum,
                    separation=separation,
                    supercell_xy=supercell_xy,
                    buffer=buffer,
                    xy_frac=xy_frac,
                    termination=termination,
                    layer_tol=layer_tol,
                    rotation=None,
                )

                metadata: Dict[str, Any] = {
                    "sample_index": sample_idx,
                    "supercell": {"nx": choice.nx, "ny": choice.ny},
                    "termination": choice.termination,
                    "termination_top": list(choice.termination_top),
                    "termination_bottom": list(choice.termination_bottom),
                    "local_refiner_used": False,
                    "local_refiner_trained": False,
                }

                if self.local_refiner is not None:
                    adsorbate_indices = list(range(len(bottom), len(bottom) + len(top)))
                    interface_normal = layering.interface_normal_unit(bottom)
                    combined = self.local_refiner.refine_structure(
                        combined,
                        adsorbate_indices=adsorbate_indices,
                        interface_normal=interface_normal,
                        refine_scope=refine_scope,
                    )
                    metadata["local_refiner_used"] = True
                    metadata["local_refiner_trained"] = bool(
                        getattr(self.local_refiner, "trained", False)
                    )

                outputs.append(InterfaceGenerationResult(
                    bottom=bottom,
                    top=top,
                    combined=combined,
                    metadata=metadata,
                ))
            except Exception as exc:
                logger.warning("Sample %d failed: %s — skipping.", sample_idx, exc)
                continue

        if not outputs:
            raise RuntimeError(
                f"All {len(results)} EGNN samples failed during interface construction. "
                "This may indicate NaN values from an unstable diffusion run. "
                "Try regenerating or using a different fullerene size."
            )

        return outputs


def _denormalize_positions(positions: np.ndarray, num_atoms: int) -> np.ndarray:
    if torch is None or denormalize_positions is None:
        return positions
    pos_tensor = torch.tensor(positions, dtype=torch.float32)
    pos_denorm = denormalize_positions(pos_tensor, int(num_atoms))
    result = pos_denorm.detach().cpu().numpy()
    # Guard: EGNN diffusion can occasionally produce NaN during unstable
    # denoising steps.  Replace NaN with zero so downstream geometry
    # calculations (diameter, supercell) don't crash.
    if np.isnan(result).any():
        import logging
        logging.getLogger(__name__).warning(
            "NaN detected in denormalized positions (%d/%d values) — replacing with 0.",
            int(np.isnan(result).sum()), result.size,
        )
        result = np.nan_to_num(result, nan=0.0)
    return result


def _adsorbate_structure_from_positions(positions: np.ndarray) -> Structure:
    if positions.size == 0:
        raise ValueError("No positions provided for adsorbate structure.")
    # NaN-safe: use nanmax to avoid propagation from bad EGNN samples
    norms = np.linalg.norm(positions, axis=1)
    max_radius = float(np.nanmax(norms)) if not np.all(np.isnan(norms)) else 0.0
    box_size = max(20.0, max_radius * 2.0 + 10.0)
    lattice = Lattice.cubic(box_size)
    species = ["C"] * positions.shape[0]
    return Structure(
        lattice,
        species,
        positions,
        coords_are_cartesian=True,
        to_unit_cell=False,
    )
